import { z } from 'zod';
import { auditableFieldsSchema, uuidSchema } from '../common';

/**
 * Routine / RoutineItem (Prompt Mestre V2 §28-29): recurring sequences a
 * person (often a child, per their AutonomyProfile) works through — e.g.
 * "manhã", "escola", "noite". Participating in a routine (completing an
 * item) never grants administrative capability — enforced by the Policy
 * Engine (completing a RoutineItem is a SCHEDULE:EDIT-scoped action on
 * that item only, never ADMIN/MANAGE), not by anything in this schema.
 */
export const routineCategorySchema = z.enum([
  'MORNING',
  'SCHOOL',
  'EVENING',
  'ACTIVITY',
  'TRAVEL',
  'HEALTH',
  'OTHER',
]);
export type RoutineCategory = z.infer<typeof routineCategorySchema>;

export const routineSchema = z
  .object({
    id: uuidSchema,
    tenantId: uuidSchema,
    subjectPersonId: uuidSchema,
    title: z.string().min(1).max(150),
    category: routineCategorySchema,
    /** RFC 5545 RRULE — which days this routine applies, e.g. weekdays. */
    rrule: z.string().nullable().optional(),
    active: z.boolean().default(true),
  })
  .merge(auditableFieldsSchema);
export type Routine = z.infer<typeof routineSchema>;

export const routineItemSchema = z
  .object({
    id: uuidSchema,
    tenantId: uuidSchema,
    routineId: uuidSchema,
    title: z.string().min(1).max(200),
    sortOrder: z.number().int().nonnegative().default(0),
    /** Materialized per-occurrence completion; null = not due/completed yet for today's occurrence. */
    completedAt: z.string().datetime({ offset: true }).nullable().optional(),
    completedByPersonId: uuidSchema.nullable().optional(),
  })
  .merge(auditableFieldsSchema);
export type RoutineItem = z.infer<typeof routineItemSchema>;

/**
 * Checklist / ChecklistItem: ad-hoc (not recurring) preparation lists,
 * typically attached to a CalendarEvent (e.g. "o que levar" for a school
 * trip) or generated by the Capture Engine from a school announcement
 * (§19).
 */
export const checklistSchema = z
  .object({
    id: uuidSchema,
    tenantId: uuidSchema,
    subjectPersonId: uuidSchema.nullable().optional(),
    linkedCalendarEventId: uuidSchema.nullable().optional(),
    title: z.string().min(1).max(200),
  })
  .merge(auditableFieldsSchema);
export type Checklist = z.infer<typeof checklistSchema>;

export const checklistItemSchema = z
  .object({
    id: uuidSchema,
    tenantId: uuidSchema,
    checklistId: uuidSchema,
    label: z.string().min(1).max(200),
    sortOrder: z.number().int().nonnegative().default(0),
    checkedAt: z.string().datetime({ offset: true }).nullable().optional(),
    checkedByPersonId: uuidSchema.nullable().optional(),
  })
  .merge(auditableFieldsSchema);
export type ChecklistItem = z.infer<typeof checklistItemSchema>;
