import { z } from 'zod';

/**
 * Shared primitives used across the domain package.
 *
 * ASSUMPTION: all external IDs are UUIDv4, generated by Postgres
 * (gen_random_uuid()) or the application layer. See section 9 of the
 * master prompt ("Usar UUIDs para IDs externos").
 */
export const uuidSchema = z.string().uuid();

export const timestampSchema = z.string().datetime({ offset: true });

/**
 * ASSUMPTION: all timestamps are stored in UTC (timestamptz in Postgres)
 * and converted to the user's local timezone at the presentation layer.
 * See section 121 ("Preferir UTC no banco para timestamps").
 */
export const auditableFieldsSchema = z.object({
  createdAt: timestampSchema,
  updatedAt: timestampSchema,
  deletedAt: timestampSchema.nullable().optional(),
});
export type AuditableFields = z.infer<typeof auditableFieldsSchema>;

/**
 * Data provenance — every fact of consequence in the platform should be
 * traceable to how it entered the system. See section 44.
 */
export const provenanceSchema = z.enum([
  'USER_DECLARED',
  'DOCUMENT_EXTRACTED',
  'PROFESSIONAL_CONFIRMED',
  'SYSTEM_GENERATED',
  'AI_INFERRED',
]);
export type Provenance = z.infer<typeof provenanceSchema>;

export const provenanceMetaSchema = z.object({
  provenance: provenanceSchema,
  confidence: z.number().min(0).max(1).nullable().optional(),
  sourceDocumentId: uuidSchema.nullable().optional(),
});
export type ProvenanceMeta = z.infer<typeof provenanceMetaSchema>;

/** Tenancy: every row that isn't purely global belongs to a Tenant. */
export const tenantScopedSchema = z.object({
  tenantId: uuidSchema,
});
